**SOW-MKI49: Neural Information Processing Systems**  
*Weeks 4 and 5: Assignment (225 points + 30 bonus points)*  
Author: Umut

In [0]:
# Group number: ...
# Student 1 name, student 1 number: ...
# Student 2 name, student 2 number: ...
# Student 3 name, student 3 number: ...

https://github.com/basameera/NIPS_week_4_5

In [1]:
from chainer import ChainList, optimizers, serializers
import chainer
import chainer.functions as F
import chainer.links as L
import numpy as np

In [2]:
chainer.print_runtime_info()

Chainer: 4.4.0
NumPy: 1.15.1
CuPy:
  CuPy Version          : 4.1.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9000
  CUDA Driver Version   : 9000
  CUDA Runtime Version  : 9000
  cuDNN Build Version   : 7102
  cuDNN Version         : 7102
  NCCL Build Version    : 1000


In [9]:
dt = np.random.randn(61, 10, 80)
print(dt.shape)
out = F.split_axis(dt, [2], 1)
print(out[0].shape)
print(out[1].shape)

(61, 10, 80)
(61, 2, 80)
(61, 8, 80)


In [36]:
np.random.seed(123)
dt = 10*np.random.randn(1, 2, 1, 4)
dt1 = F.pad(dt, ((0, 0), (0, 0), (0, 0), (1, 0)), 'constant')

print(dt1.shape)

print(dt.astype('uint8'))

print('---------------------------')

print(dt1.data.astype('uint8'))

(1, 2, 1, 5)
[[[[246   9   2 241]]

  [[251  16 232 252]]]]
---------------------------
[[[[  0 246   9   2 241]]

  [[  0 251  16 232 252]]]]


---
# Dataset

![alt text](http://i64.tinypic.com/3rkzq.jpg)

---


**WaveNet component (75 points)**

* Implement missing parts of the call method (y and z). **25 points**
* Implement residual block class. **50 points**

---
Reminder:

* One convolution layer that has 61 kernels of size 2 with no nonlinearities.
![alt text](http://i67.tinypic.com/21mgi2w.png)
![alt text](http://i67.tinypic.com/292n04y.png)
---



# Contributor - Sameera

In [13]:
class _ResidualBlock(ChainList):
    def __init__(self, dilation):
        super(_ResidualBlock, self).__init__(
            L.Convolution2D(in_channels=61, out_channels=2*61, ksize=(1, 2), dilate=dilation),
            L.Convolution2D(in_channels=61, out_channels=512, ksize=(1, 1)),
            L.Convolution2D(in_channels=61, out_channels=61, ksize=(1, 1))
        )
        
    
    def __call__(self, x):
        h = F.split_axis(self[0](x), 2, 1)
        gatedOutput = F.sigmoid(h[0]) * F.tanh(h[1])
        z = self[1](gatedOutput)
        y = self[2](gatedOutput) + x
        return y, z

    
class _WaveNet(ChainList):
    def __init__(self):
        links = (L.Convolution2D(in_channels=61, out_channels=61, ksize=(1, 2)),)
        links += tuple(_ResidualBlock((1, 2 ** (i % 6))) for i in range(6))
        links += (L.Convolution2D(512, 512, 1), L.Convolution2D(512, 3843, 1))
        super(_WaveNet, self).__init__(*links)
        '''
        QUESTIONS
        1. Why/how conv2D_7 has input of 512? If 512, should the last Res. layer has output of 512
        2. Why/How 61*61 and 2*61 comes about?
        '''
        ''' --- Structure --- (in > out)
        0.conv2D (61 -> 61)
        1.Residual (61 > 61, 512)
        2.Residual (61 > 61, 512)
        3.Residual (61 > 61, 512)
        4.Residual (61 > 61, 512)
        5.Residual (61 > 61, 512)
        6.Residual (61 > 61, 512)
        7.conv2D (512 > 512)
        8.conv2D (512 > 3843)
        '''
        
    def __call__(self, x):
        y = self[0](F.pad(x, ((0, 0), (0, 0), (0, 0), (1, 0)), 'constant'))
        z = 0
        # z - skip connection output
        # y - output of each res. layer which becomes the input to next res. layer
        
        for i in range(1, len(self) - 2):#going through Residual layers
            #pass
            y, z_hat = self[i](y)
            z += z_hat
        
        z = F.relu(self[7](z))
        z = self[8](z)
        y, z = F.split_axis(z, [61*61], 1) #if second param is an array, those positions are used as split points

        return F.reshape(y, (y.shape[0], 61, 61, y.shape[3])), F.reshape(z, (z.shape[0], 2, 61, z.shape[3]))
        # check shape sizes

---

Reminder:

![alt text](http://i68.tinypic.com/sy6mix.png)

---

**CRF-RNN component (50 points)**

* Implement missing parts of the call method (z). **25 points**
* Why is z not normalized in the last iteration? **25 points**



# Contributor - Jitendra

### https://en.wikipedia.org/wiki/Conditional_random_field

In [59]:
np.random.seed(123)
Q = np.random.randn(2, 2, 1, 4).astype('float32')
k = np.random.randn(2, 3, 1, 4).astype('float32')

In [60]:
Qv = chainer.Variable(Q)
kv = chainer.Variable(k)
out = F.batch_matmul(Qv, kv)
print(out.shape)

InvalidType: 
Invalid operation is performed in: BatchMatMul (Forward)

Expect: in_types[0].ndim <= 3
Actual: 4 > 3

In [0]:
'''
CRF - Conditional random field
This class calculate Mean-field approximation
'''
class _CRF(ChainList):
    def __init__(self):
        #ConvolutionND(ndim, in_channels, out_channels, ksize)
        super(_CRF, self).__init__(L.ConvolutionND(1, 2, 2, 1, nobias = True)) 

    def __call__(self, x, y):
        '''
        x = pairwise (61x61)
        y = unary (2x61)
        Q = psi (y)
        k = x
        
        1. Message parsing layer
           Multiply Q with k -> output a tensor (N × 2 x 61)

        2. Compatibility transform layer
           convolution with ksize=1

        3. Local update and normalization layer
           Subtract the input tensor from −ψ and normalize (softmax)

        '''
        
        #z =
        
        for i in range(5):
            #z =

            if i < 4:
                z = F.softmax(z)

        return z

**WaveCRF model (50 points)**

1. Implement missing parts of the call method (k, psi_u and Q_hat). **20 points**
2. Implement missing parts of the save and load methods (save and load model). **10 points**
3. Implement missing parts of the test and train methods (forward and/or backward propagate). **20 points**

# Contributor - Mohit

In [0]:
class WaveCRF(object):
    def __init__(self):
        self.log = {('test', 'accuracy'): (), ('test', 'loss'): (), ('training', 'accuracy'): (),
                    ('training', 'loss'): ()}
        self.model = ChainList(_WaveNet(), _CRF())
        self.optimizer = optimizers.Adam(0.0002, 0.5)

        self.optimizer.setup(self.model)

    def __call__(self, x):
        #k, psi_u =
        #Q_hat =

        return F.transpose(F.reshape(Q_hat, (x.shape[0], x.shape[3], 2, 61)), (0, 2, 3, 1))

    @classmethod 
    #https://stackoverflow.com/questions/12179271/meaning-of-classmethod-and-staticmethod-for-beginner
    def load(cls, directory):
        self = cls()
        self.log = np.load('{}/log.npy'.format(directory))
        # Load model
        serializers.load_npz('{}/model.npz'.format(directory), self.model)
        serializers.load_npz('{}/optimizer.npz'.format(directory), self.optimizer)

        return self

    def save(self, directory):
        np.save('{}/log.npy'.format(directory), self.log)
        # Save model
        serializers.save_npz('{}/model.npz'.format(directory), self.model)
        serializers.save_npz('{}/optimizer.npz'.format(directory), self.optimizer)

    def test(self, Q, x):
        with chainer.using_config('train', False):
            # Forward prop
            # Forward prop

            self.log['test', 'accuracy'] += (float(F.accuracy(Q_hat, Q).data),)
            self.log['test', 'loss'] += (float(loss.data),)

    def train(self, Q, x):
        # Forward prop
        # Forward prop

        # Backprop
        # Backprop
        # Backprop

        self.log['training', 'accuracy'] += (float(F.accuracy(Q_hat, Q).data),)
        self.log['training', 'loss'] += (float(loss.data),)

# Training

In [40]:
%matplotlib inline

import IPython
import chainer
import matplotlib
import numpy
import os
import pickle
import random
import tqdm


In [41]:
for i in tqdm.tqdm(range(int(9e6)), ascii=True, desc="NIPS-G17"):
    pass

NIPS-G17: 100%|##########| 9000000/9000000 [00:02<00:00, 3855158.43it/s]


In [42]:
for i in tqdm.tnrange(int(9e6), ascii=True, desc="NIPS-G17"):
    pass

In [0]:
batch_size = 30
epochs = 100
root = 'WaveNetModel'

In [ ]:
with open('Data/piano_rolls.p', 'rb') as f:
    piano_rolls = pickle.load(f, encoding = 'latin1')
    print(len(piano_rolls))
    for key in piano_rolls:
        
        print('{} - {}'.format(key, len(piano_rolls[key])))
        print(piano_rolls[key].shape)
        
        print(piano_rolls[key])
        

In [0]:
with open('Data/piano_rolls.p', 'rb') as f:
    piano_rolls = pickle.load(f, encoding = 'latin1') #works

keys = sorted(piano_rolls.keys())

random.seed(6)
random.shuffle(keys)

test_set = dict((key, piano_rolls[key]) for key in keys[:int(0.1 * len(keys))])
training_set = dict((key, piano_rolls[key]) for key in keys[int(0.1 * len(keys)):])
training_set_keys = list(training_set.keys())

In [0]:
waveCRF = WaveCRF()

waveCRF.model.to_gpu()

In [0]:
for epoch in tqdm.tnrange(epochs, ascii=True, desc="NIPS-G17"):
    random.shuffle(training_set_keys)

    batch = ()

    for key in tqdm.tqdm_notebook(training_set_keys, leave = False):
        i = random.randint(0, training_set[key].shape[1] - 80)
        batch += (training_set[key][32 : 93, i : i + 80],)

        if len(batch) == batch_size:
            batch = waveCRF.model.xp.array(batch)

            waveCRF.train(batch[:, :, 1:].astype('i'), batch[:, :, None, :-1].astype('f'))

            batch = ()

    for key in tqdm.tqdm_notebook(test_set, leave = False):
        batch = waveCRF.model.xp.array((test_set[key][32 : 93],))

        waveCRF.test(batch[:, :, 1:].astype('i'), batch[:, :, None, :-1].astype('f'))

    IPython.display.clear_output()

    for i, key in enumerate(waveCRF.log):
        matplotlib.pyplot.subplot(221 + i)
        matplotlib.pyplot.plot(numpy.array(waveCRF.log[key]).reshape(epoch + 1, -1).mean(1))
        matplotlib.pyplot.xlabel('iteration')
        matplotlib.pyplot.ylabel(key)

    matplotlib.pyplot.tight_layout()
    matplotlib.pyplot.show()
    os.makedirs('{}/Models/WaveCRF/{}'.format(root, epoch))
    waveCRF.save('{}/Models/WaveCRF/{}'.format(root, epoch))

**Test (50 points)**  

* Generate a number of samples, pick the best one and play it in the notebook. **50 points**

In [0]:
# Test

**Bonus question (30 points)**

* Discuss how you can improve the model (you can talk about different architectures or different ways to encode the inputs, etc.) **10 points**
* Discuss the assumptions behind the meanfield approximation and its shortcomings. **10 points**
* Prove that the iterative update equation (CRF-RNN component) is differentiable so that we can backpropagate through them. **10 points**

# Notes
- Each sample in a normal music file has a 16-bit value (65,536 probabilities per timestep). But here, that valus is compressed using the u-law (non-linear) to a 8-bit value (256 probabilities per timestep). The main reason is to reduced the number of learning parameters.
- 